language: node_js

node_js: node

env:
  global:
    - CACHE_LIB=""

matrix:
  include:
    - env:
        - CACHE_URL="dummy://"
        - TEST_FILE="test/test_dummy.coffee"
    - env:
        - CACHE_URL="memcached://localhost:11211"
        - CACHE_LIB="memcached@^2.2.2"
        - TEST_FILE="test/test_memcached.coffee"
      services:
        - memcached
    - env:
        - CACHE_URL="memcached://localhost:11211"
        - CACHE_LIB="memjs@^1.0.0-rc.1"
        - TEST_FILE="test/test_memcached.coffee"
      services:
        - memcached
    - env:
        - CACHE_URL="redis://"
        - CACHE_LIB="redis@^2.8.0"
        - TEST_FILE="test/test_redis.coffee"
      services:
        - redis-server

before_script:
  - rm package-lock.json
  - npm uninstall memcached memjs redis --nosave
  - rm package-lock.json
  - if [ $CACHE_LIB != "" ]; then npm i $CACHE_LIB; fi

script:
  - ./node_modules/.bin/mocha --require coffeescript/register --require coffee-coverage/register-istanbul --recursive --exit $TEST_FILE
  - ./node_modules/.bin/istanbul report
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
